name: Run tsx server

on: [workflow_dispatch]

jobs:
  run-tsx-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install tsx globally
        run: npm install -g tsx

      - name: Run tsx server
        run: |
          timeout 15s tsx server.ts
  run-node-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run node server
        run: |
          timeout 15s node server.js